title: The Canine Cleansing Standard (CCS-2025)
description: This is a fictive Standard to show case how to develop a standard using GitHub, SmartGit and Obsidian.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman