title: "The Canine Cleansing Standard (CCS-2025) versionToken"
description: "This fictitious Standard demonstrates how to develop a standard using GitHub, SmartGit, and Obsidian."
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman